sensors:
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.6, 2.25, 0.91]
      rpy: [0, 0, 'pi']
#logical camera placed above Bin
  logical_camera_0:
    type: logical_camera
    pose:
      xyz: [4.9861935, 1.744565, 1.8]
      rpy: [0, 'pi/2', 0]
#logical camera placed above Bin
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [3.104531, 1.744565, 1.8]
      rpy: [0, 'pi/2', 0]
#logical camera placed above Bin
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [3.104531, -1.744565, 1.8]
      rpy: [0, 'pi/2', 0]
#logical camera placed above Bin
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [4.9861935, -1.744565, 1.8]
      rpy: [0, 'pi/2', 0]
#logical camera placed above shelve
  logical_camera_4:
    type: logical_camera
    pose:
      xyz: [-3.75, 0., 2.49]
      rpy: [0, 'pi/2', 0]
#logical camera placed above shelve
  logical_camera_5:
    type: logical_camera
    pose:
      xyz: [-3.75, 3, 2.49]
      rpy: [0, 'pi/2', 0]
#logical camera placed above Conveyor belt
  logical_camera_6:
    type: logical_camera
    pose:
      xyz: [0, 2.25, 1.8]
      rpy: [0, 'pi/2', 0]
#logical camera placed above Conveyor belt
  logical_camera_7:
    type: logical_camera
    pose:
      xyz: [0, -2.25, 1.8]
      rpy: [0, 'pi/2', 0]
#logical camera placed above agv1
  logical_camera_8:
    type: logical_camera
    pose:
      xyz: [0, 7.4646, 1.75]
      rpy: [0, 'pi/2', 0]
#logical camera placed above agv2
  logical_camera_9:
    type: logical_camera
    pose:
      xyz: [0, -7.4646, 1.75]
      rpy: [0, 'pi/2', 0]
